export const blogPosts = [
  {
    id: "1",
    title: "Top 10 Electrical Safety Tips Every Homeowner Should Know",
    img: "https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg",
    author: "John Electric",
    date: "12 Sep",
    category: "Safety",
    comments: 4,
  },
  {
    id: "2",
    title: "How to Troubleshoot Common Wiring Problems",
    img: "https://images.pexels.com/photos/942316/pexels-photo-942316.jpeg",
    author: "Sarah Voltage",
    date: "05 Sep",
    category: "DIY",
    comments: 7,
  },
  {
    id: "3",
    title: "Why You Should Hire a Certified Electrician",
    img: "https://images.pexels.com/photos/4488639/pexels-photo-4488639.jpeg",
    author: "Mike Sparks",
    date: "28 Aug",
    category: "Professional Advice",
    comments: 2,
  },
  {
    id: "4",
    title: "Electrical Panel Upgrade: When and Why You Need It",
    img: "https://images.pexels.com/photos/442154/pexels-photo-442154.jpeg",
    author: "Nancy Wires",
    date: "22 Aug",
    category: "Upgrades",
    comments: 5,
  },
  {
    id: "5",
    title: "Beginner’s Guide to Circuit Breakers and Fuses",
    img: "https://images.pexels.com/photos/5974008/pexels-photo-5974008.jpeg",
    author: "Tom Fuseman",
    date: "15 Aug",
    category: "Education",
    comments: 9,
  },
  {
    id: "6",
    title: "LED Lighting: Benefits and Installation Tips",
    img: "https://images.pexels.com/photos/4488662/pexels-photo-4488662.jpeg",
    author: "Lucy Light",
    date: "09 Aug",
    category: "Lighting",
    comments: 6,
  },
  {
    id: "7",
    title: "How to Reduce Your Electricity Bill Efficiently",
    img: "https://images.pexels.com/photos/10871737/pexels-photo-10871737.jpeg",
    author: "Ben Watts",
    date: "02 Aug",
    category: "Energy Saving",
    comments: 3,
  },
  {
    id: "8",
    title: "Understanding Grounding in Electrical Systems",
    img: "https://images.pexels.com/photos/28101526/pexels-photo-28101526.jpeg",
    author: "Gina Ground",
    date: "27 Jul",
    category: "Basics",
    comments: 1,
  },
  {
    id: "9",
    title: "Signs Your Home Needs Rewiring ASAP",
    img: "https://images.pexels.com/photos/8488023/pexels-photo-8488023.jpeg",
    author: "Rick Circuit",
    date: "21 Jul",
    category: "Maintenance",
    comments: 8,
  },
  {
    id: "10",
    title: "Smart Home Electrical Setup: What You Need to Know",
    img: "https://images.pexels.com/photos/2898199/pexels-photo-2898199.jpeg",
    author: "Emily Current",
    date: "15 Jul",
    category: "Smart Tech",
    comments: 10,
  },
];
